### ISSUE TITLE
Uncaught Error: EncodingError: Unable to decode audio data

### ISSUE THREAD

**Issue by agrande** [agrande/lba2remake#162]
An error occurred on http://localhost:8080/#scene=120 [v0.0.7 (modified)]]

Stacktrace:
```
Error: EncodingError: Unable to decode audio data
    at AudioContext.<anonymous> (src/audio/index.js:234)
```

UserAgent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

Details: http://lba2remake.xesf.net/crash/crash_report_1521666361.json

**Comment by agrande** [comment]
@xesf: Have you seen that one before?

**Comment by xesf** [comment]
Yeah, I saw that before but I can't quite remember. 
The error code comes from the decoder when its parsing the audio file.

It could be 2 things I guess. 
The conversion to AAC wasn't done properly. I have done this using not the best encoding and what just as a testing, even the quality is not the best.
It could be the combination of OS+Browser not able to decode the audio type.

Looking at https://caniuse.com/#feat=aac AAC has partial support on Mozilla, so not sure this is also an issue. If it was, I would say other scenes will have the same error and not only that specific one.

I didn't manage to reproduce the issue, as another one show up. I will check that later in the evening again.

**Comment by xesf** [comment]
The issue is caused by hidden entries inside the HQR file.
Hidden entries are only used in VOX hqr files to split the voice audio files. They have this on both LBA1 and LBA2 and we believe it was a workaround to avoid big audio files, and allow them to have multiple chunks.
This entries are not described in the header file reason why the game is failing now.

A change in the HQR loading will be required.
