### ISSUE TITLE
How do I enable 3d models and control the camera?

### ISSUE THREAD

**Issue by felipesanches** [agrande/lba2remake#313]
After setting up the project in my system:
https://github.com/agrande/lba2remake/issues/312#issuecomment-655822684

Now I am exploring the editors and trying to do the same things I saw in that youtube video (playing with free camera movements, to explore the 3d scene from different angles). How do we do it? Does it need to be enabled with some command or shortcut/key combo? What are the key bindings to control the camera?

**Comment by agrande** [comment]
You can press the "C" key to switch between regular camera and free camera.

**Comment by agrande** [comment]
If you want to enable the 3D models in regular gameplay mode, you have to add iso3d=true in the url, for instance: http://localhost:8080/#iso3d=true

**Comment by agrande** [comment]
We are planning to add some UI buttons to switch between camera modes in the future, so you don't have to know the shortcut.

**Comment by felipesanches** [comment]
Great! Thanks :-)

It seems reasonable to keep this issue open then. Perhaps rename it to "Add UI to switch between camera modes"

This is a very cool project. Congratulations!

**Comment by agrande** [comment]
Well, we have a private TODO list where I do have a task for this already, we're using github issues only for user feedback, I'm keeping this closed as it doesn't require further action at the moment (since you have your question answered, and there's a task in the internal tracker). I hope you don't mind.

**Comment by felipesanches** [comment]
It feels discouraging for a potential contributor to hear that.

**Comment by agrande** [comment]
Well, we're doing the private tracker thing mostly because github issues are not convenient to work with and they became really out of sync with what we were actually doing on the project. So we're trying something a bit lighter and more focused on our specific needs.
The tracker being private doesn't mean that the list people who can access it is set in stone. It's not a VIP club. We're sharing it with anyone who's making contributions to the project.

**Comment by felipesanches** [comment]
Make it fully public, otherwise it sounds like a VIP club, regardless of what you say ;-)
